#!/usr/bin/env python3
"""Test prompt variants for iterative bounded summary updates.

This reuses captions generated by ``kv_iterative_summary_probe.py`` and only
reruns the text summary step, so it isolates whether prompt wording can keep
previous-summary information while adding a new 30s segment.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path
from typing import Any, Dict, List

import torch
from transformers import AutoProcessor, Qwen3VLForConditionalGeneration


STOPWORDS = {
    "about", "above", "after", "again", "against", "along", "also", "with", "without",
    "there", "their", "these", "those", "this", "that", "from", "into", "onto", "over",
    "under", "while", "where", "which", "being", "been", "have", "has", "had", "does",
    "display", "displays", "show", "shows", "shown", "scene", "video", "frame", "frames",
    "current", "visible", "appears", "appearing", "using", "wearing", "holding", "object",
    "person", "people", "image", "close", "view", "background", "foreground", "left",
    "right", "center", "central", "likely", "text", "visible", "caption", "chunk",
    "second", "seconds", "observation", "observations", "summary",
}


def normalize_messages(messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out = []
    for message in messages:
        content = message.get("content")
        if isinstance(content, str):
            content = [{"type": "text", "text": content}]
        out.append({**message, "content": content})
    return out


def format_captions(captions: List[Dict[str, Any]]) -> str:
    return "\n".join(f'  <m t="{c["t"]}">{c["caption"]}</m>' for c in captions)


def keywords(text: str, limit: int = 300) -> List[str]:
    words = re.findall(r"[A-Za-z][A-Za-z0-9'-]{3,}", text.lower())
    out: List[str] = []
    seen = set()
    for word in words:
        word = word.strip("'")
        if word in STOPWORDS or word in seen:
            continue
        seen.add(word)
        out.append(word)
        if len(out) >= limit:
            break
    return out


def keyword_recall(prediction: str, references: List[str]) -> float:
    ref = keywords("\n".join(references))
    if not ref:
        return 0.0
    pred = set(keywords(prediction))
    return len([w for w in ref if w in pred]) / len(ref)


def extract_ranges(text: str) -> List[tuple[int, int]]:
    ranges: List[tuple[int, int]] = []
    for match in re.finditer(r't="(\d+)(?:-(\d+))?"', text):
        a = int(match.group(1))
        b = int(match.group(2) or a)
        ranges.append((a, b))
    return ranges


def coverage_flags(text: str) -> Dict[str, Any]:
    ranges = extract_ranges(text)
    return {
        "ranges": ranges,
        "entry_count": len(ranges),
        "covers_prev": any(a < 30 for a, _ in ranges),
        "covers_current": any(b >= 30 for _, b in ranges),
        "covers_both": any(a < 30 for a, _ in ranges) and any(b >= 30 for _, b in ranges),
    }


VARIANTS: Dict[str, str] = {
    "baseline_cover_both": """Compress streaming video memory into one bounded historical state summary.
Target exactly 4 entries. Output at most 6 entries.
Cover BOTH previous-summary events and current-segment events.
Each entry should be an abstract stage/event/state, not a caption.
Prefer broad ranges. Use only:
<global_state_summary>
  <m t="a-b">short event/state.</m>
</global_state_summary>""",
    "fixed_quota": """Update bounded video memory.
If previous_summary is not empty, output exactly 4 entries:
- first 2 entries must summarize/carry previous_summary with time ranges before the current segment;
- last 2 entries must summarize current_segment_captions with current-segment time ranges.
Do not output only current-segment entries.
Each entry <=18 words. Use only <global_state_summary> with <m t="a-b"> entries.""",
    "append_only": """Append-only memory update.
If previous_summary is present, copy its important entries forward before adding new current-segment entries.
Do not delete earlier time ranges in this update.
Then add 1-3 broad entries for current_segment_captions.
If output would exceed 6 entries, merge current entries first; do not drop previous entries.
Use only <global_state_summary> with <m t="a-b"> entries.""",
    "priority_previous": """Maintain long-horizon video memory.
previous_summary is high-priority compressed memory. current_segment_captions are detailed new evidence.
If previous_summary is present, at least half of the output entries must cover previous_summary time ranges.
The rest should cover current_segment_captions.
Output 4-6 entries, <=18 words each, only inside <global_state_summary>.""",
    "copy_then_add": """Memory update with strict carry-forward.
If previous_summary is present, copy all of its <m> entries unchanged, then append 1-2 new <m> entries for current_segment_captions.
Do not rewrite, remove, or merge previous_summary entries in this test.
If previous_summary is empty, summarize current_segment_captions into 3-4 entries.
Use only <global_state_summary>.""",
    "two_bank": """Create a two-bank bounded memory but output it as one <global_state_summary>.
Bank A: carried history from previous_summary, 2 entries.
Bank B: new progress from current_segment_captions, 2 entries.
The final output must contain entries from both banks when previous_summary exists.
Use broad time ranges and <=18 words per entry.""",
    "immutable_copy_plus_delta": """The previous_summary is immutable long-term memory.
If previous_summary is present, copy every previous <m> entry exactly, preserving its t range and text.
Then append exactly 2 new <m> entries summarizing current_segment_captions.
The final output must contain both copied previous entries and new current entries.
Use only <global_state_summary>. Do not rewrite previous entries.""",
    "source_slots": """Output exactly 5 entries when previous_summary exists:
3 entries must have time ranges from previous_summary and summarize/copy prior memory.
2 entries must have time ranges from current_segment_captions.
Order entries chronologically. Do not output all entries from one source.
Use only <global_state_summary> with <m t="a-b">text</m> entries.""",
    "constraint_gate": """Generate a valid bounded memory update.
Hard constraints:
1. Total entries: 4 to 6.
2. At least 2 entries must have t ranges before the current segment.
3. At least 2 entries must have t ranges inside the current segment.
4. If any constraint would be violated, revise before output.
Use broad ranges and <=18 words per entry. Output only <global_state_summary>.""",
    "schema_comment": """Fill this schema exactly:
<global_state_summary>
  <m t="prev_range_1">previous event/state 1</m>
  <m t="prev_range_2">previous event/state 2</m>
  <m t="current_range_1">current event/state 1</m>
  <m t="current_range_2">current event/state 2</m>
</global_state_summary>
Replace placeholders with real ranges and concise text.
Previous ranges must come from previous_summary; current ranges must come from current_segment_captions.""",
    "two_stage_current_then_merge": """SPECIAL_TWO_STAGE""",
}


def build_prompt(
    variant: str,
    previous_summary: str,
    captions: List[Dict[str, Any]],
    segment_range: List[int],
) -> str:
    prev = previous_summary.strip() or '  <m t="none">No previous summary.</m>'
    return f"""Instruction:
{VARIANTS[variant]}
Stop immediately after </global_state_summary>.

<previous_summary>
{prev}
</previous_summary>

<current_segment_captions t="{segment_range[0]}-{segment_range[1]}">
{format_captions(captions)}
</current_segment_captions>"""


def build_current_only_prompt(captions: List[Dict[str, Any]], segment_range: List[int]) -> str:
    return f"""Instruction:
Summarize current_segment_captions into exactly 2 broad memory entries.
Each entry must be <=18 words and must use a real time range from the current segment.
Do not copy individual captions. Merge adjacent repeated actions.
Output only:
<current_segment_summary>
  <m t="a-b">short event/state.</m>
  <m t="c-d">short event/state.</m>
</current_segment_summary>

<current_segment_captions t="{segment_range[0]}-{segment_range[1]}">
{format_captions(captions)}
</current_segment_captions>"""


def build_merge_summaries_prompt(previous_summary: str, current_summary: str) -> str:
    prev = previous_summary.strip() or '  <m t="none">No previous summary.</m>'
    return f"""Instruction:
Merge two already-compressed memories.
The previous summary and current summary now have comparable token budgets.
Copy all useful entries from previous_summary and current_segment_summary.
Output 4-6 chronological entries. Each entry <=18 words.
Do not expand an entry back into per-second captions.
Use only <global_state_summary>.

<previous_summary>
{prev}
</previous_summary>

<current_segment_summary>
{current_summary.strip()}
</current_segment_summary>"""


@torch.inference_mode()
def generate(model, processor, prompt: str, *, device: str, max_new_tokens: int) -> Dict[str, Any]:
    messages = normalize_messages([
        {"role": "system", "content": "You update bounded streaming-video memory."},
        {"role": "user", "content": prompt},
    ])
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[text], return_tensors="pt").to(device)
    t0 = time.time()
    output_ids = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=processor.tokenizer.pad_token_id or processor.tokenizer.eos_token_id,
    )
    new_ids = output_ids[:, inputs["input_ids"].shape[1]:]
    return {
        "input_tokens": int(inputs["input_ids"].shape[-1]),
        "new_tokens": int(new_ids.shape[-1]),
        "latency_sec": time.time() - t0,
        "text": processor.tokenizer.decode(new_ids[0], skip_special_tokens=True).strip(),
    }


def load_model(model_path: str, device: str, attn: str):
    processor = AutoProcessor.from_pretrained(model_path, trust_remote_code=True)
    model = Qwen3VLForConditionalGeneration.from_pretrained(
        model_path,
        dtype=torch.bfloat16,
        device_map={"": device},
        attn_implementation=attn,
    ).eval()
    return model, processor


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--caption-result", type=Path, default=Path("output/base_summary_iteration_probe/kv_iter30_banana_fps2_freshsummary.json"))
    parser.add_argument("--model", default="/home/tione/notebook/gaozhenkun/model/Qwen3-VL-2B-Instruct")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--attn-implementation", default="sdpa", choices=["sdpa", "flash_attention_2"])
    parser.add_argument("--max-new-tokens", type=int, default=224)
    parser.add_argument("--variants", nargs="*", default=list(VARIANTS))
    parser.add_argument("--fixed-previous-summary-result", type=Path, default=None)
    parser.add_argument("--fixed-previous-segment-index", type=int, default=0)
    parser.add_argument("--target-segment-index", type=int, default=None)
    parser.add_argument("--out", type=Path, default=Path("output/base_summary_iteration_probe/summary_prompt_variants_banana.json"))
    args = parser.parse_args()

    data = json.loads(args.caption_result.read_text(encoding="utf-8"))
    segments = data["segments"]
    model, processor = load_model(args.model, args.device, args.attn_implementation)

    fixed_previous_summary = ""
    if args.fixed_previous_summary_result is not None:
        fixed = json.loads(args.fixed_previous_summary_result.read_text(encoding="utf-8"))
        fixed_previous_summary = fixed["segments"][args.fixed_previous_segment_index]["summary"]

    rows: List[Dict[str, Any]] = []
    for variant in args.variants:
        previous_summary = fixed_previous_summary
        variant_rows: List[Dict[str, Any]] = []
        if args.target_segment_index is not None:
            target_segments = [segments[args.target_segment_index]]
        elif fixed_previous_summary:
            target_segments = [segments[args.fixed_previous_segment_index + 1]]
        else:
            target_segments = segments[:2]
        for seg in target_segments:
            intermediate: Dict[str, Any] | None = None
            if variant == "two_stage_current_then_merge":
                current_prompt = build_current_only_prompt(seg["captions"], seg["segment_range"])
                current_out = generate(
                    model,
                    processor,
                    current_prompt,
                    device=args.device,
                    max_new_tokens=args.max_new_tokens,
                )
                merge_prompt = build_merge_summaries_prompt(previous_summary, current_out["text"])
                out = generate(
                    model,
                    processor,
                    merge_prompt,
                    device=args.device,
                    max_new_tokens=args.max_new_tokens,
                )
                intermediate = current_out
            else:
                prompt = build_prompt(variant, previous_summary, seg["captions"], seg["segment_range"])
                out = generate(model, processor, prompt, device=args.device, max_new_tokens=args.max_new_tokens)
            prev_refs = [previous_summary] if previous_summary else []
            current_refs = [c["caption"] for c in seg["captions"]]
            flags = coverage_flags(out["text"])
            row = {
                "variant": variant,
                "segment_range": seg["segment_range"],
                **out,
                **flags,
                "recall_previous": keyword_recall(out["text"], prev_refs) if prev_refs else None,
                "recall_current": keyword_recall(out["text"], current_refs),
            }
            if intermediate is not None:
                row["intermediate_current_summary"] = intermediate
            variant_rows.append(row)
            previous_summary = out["text"]
        rows.extend(variant_rows)
        print_rows = []
        for row in variant_rows:
            print_rows.append({
                "range": row["segment_range"],
                "entries": row["entry_count"],
                "covers_both": row["covers_both"],
                "recall_previous": (
                    round(row["recall_previous"], 3)
                    if row["recall_previous"] is not None
                    else None
                ),
                "recall_current": round(row["recall_current"], 3),
                "text": row["text"],
            })
        print(json.dumps({
            "variant": variant,
            "segments": print_rows,
        }, ensure_ascii=False, indent=2), flush=True)

    result = {
        "caption_result": str(args.caption_result),
        "model": args.model,
        "variants": args.variants,
        "rows": rows,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"out": str(args.out), "rows": len(rows)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
