#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT=/home/tione/notebook/gaozhenkun/hzh/ThinkStream
VERL_ROOT="${PROJECT_ROOT}/verl"
DATA_ROOT="${PROJECT_ROOT}/data/agent_v5/batch12345_bank_scheme_strat_sft700_dagger450_rl850_val150_test150_v1259"
cd "${PROJECT_ROOT}"

RUN_NAME=grpo-v1259-imagepad-timeonly-recurrent-sft400-fix11-trainfast-20260509_0835
OUT="${PROJECT_ROOT}/output/${RUN_NAME}"
CUSTOM_MODULE="${VERL_ROOT}/recipe_thinkstream/thinkstream.py"
AGENT_LOOP_CONFIG="${VERL_ROOT}/recipe_thinkstream/configs/agent_loops.yaml"
mkdir -p "${OUT}/audit"
RUNTIME_ROOT="${RUNTIME_ROOT:-${PROJECT_ROOT}/.runtime/${RUN_NAME}}"
mkdir -p "${RUNTIME_ROOT}"/{tmp,ray,hf,torch,triton,xdg}

# Keep runtime spill/cache files on the large hzh filesystem. Ray/vLLM can
# otherwise fill /tmp during long recurrent rollouts.
export TMPDIR="${TMPDIR:-${RUNTIME_ROOT}/tmp}"
export TMP="${TMP:-${TMPDIR}}"
export TEMP="${TEMP:-${TMPDIR}}"
export RAY_TMPDIR="${RAY_TMPDIR:-${RUNTIME_ROOT}/ray}"
export HF_HOME="${HF_HOME:-${RUNTIME_ROOT}/hf}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-${HF_HOME}/datasets}"
export TORCH_HOME="${TORCH_HOME:-${RUNTIME_ROOT}/torch}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-${RUNTIME_ROOT}/triton}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${RUNTIME_ROOT}/xdg}"

export PYTHONPATH="${VERL_ROOT}:${PROJECT_ROOT}:${PYTHONPATH:-}"
export PYTHONUNBUFFERED=1
export WANDB_MODE=offline
export VLLM_ALLREDUCE_USE_SYMM_MEM=0
export TOKENIZERS_PARALLELISM=true
export NCCL_DEBUG=WARN
export VLLM_LOGGING_LEVEL=WARN
export THINKSTREAM_EXPERIMENT_NAME="${RUN_NAME}"
export THINKSTREAM_TRAJ_INDEX_PATH="${DATA_ROOT}/final/train_rl_trajectories.jsonl"
export THINKSTREAM_FRAMES_ROOT="${DATA_ROOT}/frames"
export THINKSTREAM_FRAME_PROTOCOL=video_meta
export THINKSTREAM_RENDER_LAYOUT=timeline_video_imagepad
export THINKSTREAM_RECURRENT_MODE="${THINKSTREAM_RECURRENT_MODE:-recurrent}"
export THINKSTREAM_RL_EPISODE_MODE="${THINKSTREAM_RL_EPISODE_MODE:-full}"
export THINKSTREAM_SEGMENT_PRE_CONTEXT="${THINKSTREAM_SEGMENT_PRE_CONTEXT:-8}"
export THINKSTREAM_SEGMENT_POST_CONTEXT="${THINKSTREAM_SEGMENT_POST_CONTEXT:-8}"
export THINKSTREAM_SEGMENT_MAX_CHUNKS="${THINKSTREAM_SEGMENT_MAX_CHUNKS:-64}"
export MULTI_Q="${MULTI_Q:-1}"
export THINKSTREAM_MAX_RECALL_PER_CHUNK="${THINKSTREAM_MAX_RECALL_PER_CHUNK:-1}"
export THINKSTREAM_RL_ROLLOUT_AUDIT_PATH="${OUT}/audit/rl_rollout_samples.jsonl"
export THINKSTREAM_RL_ROLLOUT_AUDIT_PROB=1.0
export THINKSTREAM_RL_ROLLOUT_AUDIT_MAX=6000
export THINKSTREAM_RL_ROLLOUT_AUDIT_MAX_TURNS=520
export THINKSTREAM_RL_ROLLOUT_AUDIT_FINAL_ONLY=1
export MAX_NEW_TOKEN="${MAX_NEW_TOKEN:-4096}"
export MAX_CHUNKS="${MAX_CHUNKS:-420}"
export MAX_ACTION_TOKENS="${MAX_ACTION_TOKENS:-256}"
export MAX_COMPRESS_ACTION_TOKENS="${MAX_COMPRESS_ACTION_TOKENS:-1024}"
export THINKSTREAM_MAX_TOKENS_PER_ACTION="${MAX_ACTION_TOKENS}"
export THINKSTREAM_COMPRESS_MAX_TOKENS_PER_ACTION="${MAX_COMPRESS_ACTION_TOKENS}"
export BATCH_SIZE="${BATCH_SIZE:-1}"
export GROUP_SIZE="${GROUP_SIZE:-8}"
export TP_SIZE="${TP_SIZE:-2}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-65536}"
export LOG_PROB_MAX_TOKEN_LEN_PER_GPU="${LOG_PROB_MAX_TOKEN_LEN_PER_GPU:-65536}"
export DATA_SHUFFLE="${DATA_SHUFFLE:-false}"
export DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-0}"

/home/tione/notebook/gaozhenkun/hzh/envs/thinkstream/bin/python -m verl.trainer.main_ppo \
  --config-path="${VERL_ROOT}/recipe_thinkstream/configs" \
  --config-name=thinkstream_grpo \
  data.train_files="${DATA_ROOT}/rendered/video_meta_timeline_video_imagepad/train_rl_multi_q.parquet" \
  "data.val_files=[${DATA_ROOT}/rendered/video_meta_timeline_video_imagepad/val_rl_multi_q.parquet]" \
  "data.custom_cls.path=${CUSTOM_MODULE}" \
  data.custom_cls.name=CustomRLHFDataset \
  data.val_batch_size="${BATCH_SIZE}" \
  data.train_batch_size="${BATCH_SIZE}" \
  data.max_prompt_length=16384 \
  data.max_response_length=4096 \
  data.return_raw_chat=True \
  data.filter_overlong_prompts=True \
  data.shuffle="${DATA_SHUFFLE}" \
  data.dataloader_num_workers="${DATALOADER_NUM_WORKERS}" \
  ray_kwargs.ray_init._temp_dir="${RAY_TMPDIR}" \
  ray_kwargs.ray_init.runtime_env.env_vars.TMPDIR="${TMPDIR}" \
  ray_kwargs.ray_init.runtime_env.env_vars.RAY_TMPDIR="${RAY_TMPDIR}" \
  ray_kwargs.ray_init.runtime_env.env_vars.HF_HOME="${HF_HOME}" \
  ray_kwargs.ray_init.runtime_env.env_vars.TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE}" \
  ray_kwargs.ray_init.runtime_env.env_vars.HF_DATASETS_CACHE="${HF_DATASETS_CACHE}" \
  ray_kwargs.ray_init.runtime_env.env_vars.TORCH_HOME="${TORCH_HOME}" \
  ray_kwargs.ray_init.runtime_env.env_vars.TRITON_CACHE_DIR="${TRITON_CACHE_DIR}" \
  ray_kwargs.ray_init.runtime_env.env_vars.XDG_CACHE_HOME="${XDG_CACHE_HOME}" \
  algorithm.adv_estimator=grpo \
  algorithm.kl_ctrl.kl_coef=0.0 \
  actor_rollout_ref.model.path="${PROJECT_ROOT}/output/agent-sft-v1259-timeline-video-imagepad-timeonly-bs2-fix2-20260508_1725" \
  actor_rollout_ref.model.use_remove_padding=True \
  actor_rollout_ref.model.use_fused_kernels=True \
  actor_rollout_ref.actor.optim.lr=5e-7 \
  actor_rollout_ref.actor.ppo_mini_batch_size=1 \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.actor.use_kl_loss=False \
  actor_rollout_ref.actor.kl_loss_coef=0.0 \
  actor_rollout_ref.actor.kl_loss_type=low_var_kl \
  actor_rollout_ref.actor.entropy_coeff=0.0 \
  actor_rollout_ref.actor.use_dynamic_bsz=True \
  actor_rollout_ref.actor.ppo_max_token_len_per_gpu="${PPO_MAX_TOKEN_LEN_PER_GPU}" \
  actor_rollout_ref.actor.freeze_vision_tower=True \
  actor_rollout_ref.actor.fsdp_config.param_offload=true \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
  actor_rollout_ref.actor.checkpoint.save_contents=[model,hf_model,optimizer,extra] \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
  actor_rollout_ref.ref.log_prob_max_token_len_per_gpu="${LOG_PROB_MAX_TOKEN_LEN_PER_GPU}" \
  actor_rollout_ref.ref.fsdp_config.param_offload=True \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.mode=async \
  actor_rollout_ref.rollout.n="${GROUP_SIZE}" \
  actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.55 \
  actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
  actor_rollout_ref.rollout.max_model_len=32768 \
  actor_rollout_ref.rollout.limit_images=64 \
  actor_rollout_ref.rollout.limit_videos=2 \
  actor_rollout_ref.rollout.enforce_eager=True \
  actor_rollout_ref.rollout.free_cache_engine=True \
  actor_rollout_ref.rollout.enable_chunked_prefill=True \
  actor_rollout_ref.rollout.enable_prefix_caching=True \
  +actor_rollout_ref.rollout.engine_kwargs.vllm.mm_processor_cache_gb=512 \
  actor_rollout_ref.rollout.response_length=4096 \
  actor_rollout_ref.rollout.prompt_length=16384 \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
  actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu="${LOG_PROB_MAX_TOKEN_LEN_PER_GPU}" \
  actor_rollout_ref.rollout.multi_turn.enable=True \
  actor_rollout_ref.rollout.multi_turn.max_assistant_turns=420 \
  actor_rollout_ref.rollout.multi_turn.max_user_turns=420 \
  actor_rollout_ref.rollout.multi_turn.max_parallel_calls=1 \
  "actor_rollout_ref.rollout.agent.agent_loop_config_path=${AGENT_LOOP_CONFIG}" \
  "reward.custom_reward_function.path=${CUSTOM_MODULE}" \
  reward.custom_reward_function.name=compute_score \
  trainer.critic_warmup=0 \
  'trainer.logger=["console","wandb"]' \
  trainer.val_before_train=False \
  trainer.n_gpus_per_node=8 \
  trainer.nnodes=1 \
  trainer.save_freq=50 \
  trainer.test_freq=50 \
  trainer.total_epochs=1 \
  trainer.project_name=thinkstream-v12 \
  "trainer.experiment_name=${RUN_NAME}" \
  "trainer.default_local_dir=${OUT}" \
  2>&1 | tee "${OUT}/train.log"
